behaviors:
  LevelGeneration:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 8000
      learning_rate: 3e-4
      beta: 5e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.7
        network_settings:
          hidden_units: 128
          num_layers: 2
      curiosity:
        strength: 0.9
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 2
        learning_rate: 3e-4
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 1000
    summary_freq: 20000
